print("_"*90)
print("|"+" "*88+"|")
print("|  MENU "+" "*81+"|")
print("|"+" "*88+"|")
print("|"+" "*88+"|")
print("|         Bem-vindo ao seu banco: "+" "*55+"|")
print("|"+" "*88+"|")
print("|"+" "*88+"|")
print("|         Escolha uma opção: "+" "*60+"|")
print("|         0 - Criar conta: "+" "*62+"|")
print("|         1 - Verificar Saldo: "+" "*58+"|")
print("|         2 - Depositar Dinheiro: "+" "*55+"|")
print("|         3 - Sacar Dinheiro: "+" "*59+"|")
print("|         4 - Sair: "+" "*69+"|")
print("|"+" "*88+"|")
print("-"*90)